### ISSUE TITLE
The output is None

### ISSUE THREAD

**Issue by JJun-Guo** [synodriver/rsilk#2]
Hi , the "output = rsilk.decode" is None

**Comment by synodriver** [comment]
Can you give your code example？

**Comment by JJun-Guo** [comment]
> Can you give your code example？
[
[600ab843a2c8e7d4fa9.aud.silk.zip](https://github.com/synodriver/rsilk/files/10672010/600ab843a2c8e7d4fa9.aud.silk.zip)
](url)
import rsilk
with open("600ab843a2c8e7d4fa9.aud.silk", "rb") as f:
    data = f.read()
output = rsilk.decode(data, 24000)
with open("output.pcm", "wb") as f:
    f.write(output)

**Comment by synodriver** [comment]
Ok，that is because you missed some params.

**Comment by synodriver** [comment]
Well, your first silk file is empty, and the second is not a vallid silk file. How did you generate them?

**Comment by synodriver** [comment]
![image](https://user-images.githubusercontent.com/50922489/218295753-fb0f149a-de85-486c-8877-1fea36b1ea6e.png)
Real silk file won't look like this.

**Comment by JJun-Guo** [comment]
> Ok，that is because you missed some params.

how to choose the params? can you give the sample generously？

**Comment by synodriver** [comment]
Generally it's depend on how you made this silk file. But in your example the silk file is not valid.

**Comment by JJun-Guo** [comment]
> Generally it's depend on how you made this silk file. But in your example the silk file is not valid.
[cj_wx_内_普通话_0001.silk.zip](https://github.com/synodriver/rsilk/files/10835711/cj_wx_._._0001.silk.zip)
how about this file,can u try?

**Comment by synodriver** [comment]
This one is valid, can pass both pysilk and rsilk tests
![image](https://user-images.githubusercontent.com/50922489/230893596-7066a3c1-618a-4319-8b2b-8fef86e1d2a1.png)

**Comment by synodriver** [comment]
By the way, there is another silk codec [pysilk](https://github.com/synodriver/pysilk), which is designed to iterate over silk files to ignore size limit. It can encode and decode silk files much larger than memory on a PC, with almost the same performance as ```rsilk```, and runs on both CPython and PyPy.
